security:
    providers:
        user_repository:
            id: appbundle.repository.user
        in_memory:
            memory: ~

    firewalls:
            secured_area:
                pattern:    ^/
                anonymous: ~
                form_login:
                    login_path: /connexion
                    check_path: /connexion_check
                logout:
                    path:   /deconnexion
                    target: /

        access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/me, roles: ROLE_USER }

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
